apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvvol-1
  namespace: ms   
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 10Mi
  persistentVolumeReclaimPolicy: Retain    
  nfs:
    path: /opt/sfw
    server: k8scp
    readOnly: false  
