kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: sa-role-binding
  namespace: ms
subjects:
- kind: ServiceAccount
  name: default
  namespace: msjava
roleRef:
  kind: Role
  name: developer
  apiGroup: ""
